// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWS9AnGVe5kffXPUD8qajCPjcU8t5C3s',
    appId: '1:1041559862316:android:84d2919f42529eebf46589',
    messagingSenderId: '1041559862316',
    projectId: 'uas-praktikum-mobile-dev',
    storageBucket: 'uas-praktikum-mobile-dev.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5KU_G7iE9XIxHrwKl0ZzMNhiyOfsKgBo',
    appId: '1:1041559862316:web:e0687af09378cf7bf46589',
    messagingSenderId: '1041559862316',
    projectId: 'uas-praktikum-mobile-dev',
    authDomain: 'uas-praktikum-mobile-dev.firebaseapp.com',
    storageBucket: 'uas-praktikum-mobile-dev.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGKWFjNW58cHar1HFmP6XrGdqG5tW5VmM',
    appId: '1:1041559862316:ios:027b39290fbce210f46589',
    messagingSenderId: '1041559862316',
    projectId: 'uas-praktikum-mobile-dev',
    storageBucket: 'uas-praktikum-mobile-dev.firebasestorage.app',
    iosBundleId: 'com.example.uasPraktikum',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGKWFjNW58cHar1HFmP6XrGdqG5tW5VmM',
    appId: '1:1041559862316:ios:027b39290fbce210f46589',
    messagingSenderId: '1041559862316',
    projectId: 'uas-praktikum-mobile-dev',
    storageBucket: 'uas-praktikum-mobile-dev.firebasestorage.app',
    iosBundleId: 'com.example.uasPraktikum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5KU_G7iE9XIxHrwKl0ZzMNhiyOfsKgBo',
    appId: '1:1041559862316:web:ed3b77d55ba7dc86f46589',
    messagingSenderId: '1041559862316',
    projectId: 'uas-praktikum-mobile-dev',
    authDomain: 'uas-praktikum-mobile-dev.firebaseapp.com',
    storageBucket: 'uas-praktikum-mobile-dev.firebasestorage.app',
  );

}